#!/bin/bash

dotfile_dir=${HOME}/dotfiles
exclude_list=("LICENSE" "mklinks" "README.md")

chmod --recursive --silent g= ${dotfile_dir}

cd ${dotfile_dir} &&\
  files=($(find * -type f)) &&\
  directories=($(find * -type d)) ||\
  exit 1

for item in "${exclude_list[@]}"; do
  files=(${files[@]//${item}})
done

for dir in "${directories[@]}"; do
  mkdir -p ${HOME}/${dir}
done

for file in "${files[@]}"; do
  ln --force --relative --symbolic "${dotfile_dir}/${file}" "${HOME}/.${file}"
done

