#!/bin/bash

if [[ x${1} =~ ^(x--force|xforce|x-f)$ ]]; then
  set -- "--force"
else
  set --
fi

dotfile_dir=${HOME}/dotfiles
exclude_list=("LICENSE" "mklinks" "README.md")

chmod --recursive --silent go= ${dotfile_dir}

cd ${dotfile_dir} &&\
  files=($(find * -type f)) &&\
  directories=($(find * -type d)) ||\
  exit 1

for item in "${exclude_list[@]}"; do
  files=(${files[@]//${item}})
done

for dir in "${directories[@]}"; do
  mkdir --verbose --parents ${HOME}/.${dir}
done

for file in "${files[@]}"; do
  ln --verbose ${1} --relative --symbolic "${dotfile_dir}/${file}" "${HOME}/.${file}" 2> /dev/null
done

exit 0
