#!/bin/bash

exclude_list=("LICENSE" "mklinks" "README.md")
dotfiles=($(ls -d *))

for entry in "${exclude_list[@]}"; do
  dotfiles=(${dotfiles[@]//*${entry}*})
done

for file in "${dotfiles[@]}"; do
  ln -s "${file}" "${HOME}/.${file}"
done

